### ISSUE TITLE
Cannot export anything. Location Unknown Error: -1

### ISSUE THREAD

**Issue by ReubenU** [godotengine/collada-exporter#110]
![BetterExporter_MassiveError](https://user-images.githubusercontent.com/15871822/62021146-d007ed00-b193-11e9-9965-68ff49d4642c.png)

**Comment by MaywormIII** [comment]
I'm having probably the same problem. Here are my console messages:
`Traceback (most recent call last):
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/__init__.py", line 173, in execute
    return export_dae.save(self, context, **keywords)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 2068, in save
    exp.export()
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1976, in export
    self.export_scene()
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1621, in export_scene
    self.export_node(obj, 2)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1571, in export_node
    self.export_node(x, il)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1558, in export_node
    self.export_mesh_node(node, il)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1142, in export_mesh_node
    meshdata = self.export_mesh(node, armature)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 642, in export_mesh
    mesh.update(calc_edges=False, calc_edges_loose=False, calc_loop_triangles=True)# 2.80
TypeError: Mesh.update(): takes at most 2 arguments, got 3

location: <unknown location>:-1`

**Comment by MaywormIII** [comment]
I'm having probably the same problem. Here are my console messages. Those show when I try to export
`test`
`
Traceback (most recent call last):
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/__init__.py", line 173, in execute
    return export_dae.save(self, context, **keywords)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 2068, in save
    exp.export()
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1976, in export
    self.export_scene()
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1621, in export_scene
    self.export_node(obj, 2)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1571, in export_node
    self.export_node(x, il)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1558, in export_node
    self.export_mesh_node(node, il)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1142, in export_mesh_node
    meshdata = self.export_mesh(node, armature)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 642, in export_mesh
    mesh.update(calc_edges=False, calc_edges_loose=False, calc_loop_triangles=True)# 2.80
TypeError: Mesh.update(): takes at most 2 arguments, got 3

location: <unknown location>:-1
`

**Comment by MaywormIII** [comment]
I'm having probably the same problem. Here are my console messages. Those show when I try to export something.

`Traceback (most recent call last):
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/__init__.py", line 173, in execute
    return export_dae.save(self, context, **keywords)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 2068, in save
    exp.export()
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1976, in export
    self.export_scene()
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1621, in export_scene
    self.export_node(obj, 2)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1571, in export_node
    self.export_node(x, il)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1558, in export_node
    self.export_mesh_node(node, il)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1142, in export_mesh_node
    meshdata = self.export_mesh(node, armature)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 642, in export_mesh
    mesh.update(calc_edges=False, calc_edges_loose=False, calc_loop_triangles=True)# 2.80
TypeError: Mesh.update(): takes at most 2 arguments, got 3`

`location: <unknown location>:-1`

**Comment by MaywormIII** [comment]
Traceback (most recent call last):
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/__init__.py", line 173, in execute
    return export_dae.save(self, context, **keywords)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 2068, in save
    exp.export()
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1976, in export
    self.export_scene()
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1621, in export_scene
    self.export_node(obj, 2)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1571, in export_node
    self.export_node(x, il)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1558, in export_node
    self.export_mesh_node(node, il)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 1142, in export_mesh_node
    meshdata = self.export_mesh(node, armature)
  File "/home/mayworm/Desktop/Aplicações/Blender_v2.82/blender-2.82-linux64/2.82/scripts/addons/io_scene_dae/export_dae.py", line 642, in export_mesh
    mesh.update(calc_edges=False, calc_edges_loose=False, calc_loop_triangles=True)# 2.80
TypeError: Mesh.update(): takes at most 2 arguments, got 3

location: <unknown location>:-1

**Comment by Calinou** [comment]
@MaywormIII The Collada exporter in this repository hasn't been updated for Blender 2.8 yet. Moreover, I'm not sure if any of the forks have updated the Godot Export Manager, which is a separate add-on.

**Comment by Xekkel** [comment]
@Calinou Is there a work around for fix for this bug? Is using and older version of Blender a fix? I'm kind of stuck right now unable to put animations into my Godot project, because of this same error trace. I'm not sure what to do because I'm having problems with .fbx and .glb as well.

**Comment by set-killer** [comment]
@Xekkel for Godot projects you can use the [Godot Export Manager](https://github.com/godotengine/godot-blender-exporter).

**Comment by gsss124** [comment]
I was stuck at the same error, the solution is quite simple. The error says "TypeError: Mesh.update(): takes at most 2 arguments, got 3", for file **export_dae.py**. A look-up on DuckDuckGo told me that Mesh.update() only takes calc_edges and calc_edges_loose. So, open **export_dae.py** in any text editor, goto line 642 and delete _, calc_loop_triangles=True_ from inside the brackets of Mesh.update() and save it. Once I did that, BetterCollada exported the mesh with animation and if I check copy images, it exported images also. The only problem is the shader, which is too bright, which makes the material color look faded. Note that I have tested this on Linux, with extracted version of Blender 2.83 and Godot 3.2.1. Better Collada Add-on for 2.8x can be downloaded from here: [](https://github.com/artellblender/collada-exporter-2.8). Enjoy Godot :)
