### ISSUE TITLE
multiple errors when using

### ISSUE THREAD

**Issue by takedabro** [godotengine/collada-exporter#127]
i tried using it and followed exactly what they said to do, but it is giving me multiple errors when i use it 
here are the errors:
`Python: Traceback (most recent call last):
  File "D:\blender\blender-2.91.0-windows64\blender-2.91.0-windows64\2.91\scripts\addons\io_scene_dae\__init__.py", line 173, in execute
    return export_dae.save(self, context, **keywords)
  File "D:\blender\blender-2.91.0-windows64\blender-2.91.0-windows64\2.91\scripts\addons\io_scene_dae\export_dae.py", line 2068, in save
    exp.export()
  File "D:\blender\blender-2.91.0-windows64\blender-2.91.0-windows64\2.91\scripts\addons\io_scene_dae\export_dae.py", line 1976, in export
    self.export_scene()
  File "D:\blender\blender-2.91.0-windows64\blender-2.91.0-windows64\2.91\scripts\addons\io_scene_dae\export_dae.py", line 1621, in export_scene
    self.export_node(obj, 2)
  File "D:\blender\blender-2.91.0-windows64\blender-2.91.0-windows64\2.91\scripts\addons\io_scene_dae\export_dae.py", line 1571, in export_node
    self.export_node(x, il)
  File "D:\blender\blender-2.91.0-windows64\blender-2.91.0-windows64\2.91\scripts\addons\io_scene_dae\export_dae.py", line 1558, in export_node
    self.export_mesh_node(node, il)
  File "D:\blender\blender-2.91.0-windows64\blender-2.91.0-windows64\2.91\scripts\addons\io_scene_dae\export_dae.py", line 1142, in export_mesh_node
    meshdata = self.export_mesh(node, armature)
  File "D:\blender\blender-2.91.0-windows64\blender-2.91.0-windows64\2.91\scripts\addons\io_scene_dae\export_dae.py", line 642, in export_mesh
    mesh.update(calc_edges=False, calc_edges_loose=False, calc_loop_triangles=True)# 2.80
TypeError: Mesh.update(): takes at most 2 arguments, got 3

location: <unknown location>:-1

`

**Comment by Calinou** [comment]
The upstream version of this add-on doesn't support Blender 2.80 or later. See https://github.com/godotengine/collada-exporter/issues/96.
