### ISSUE TITLE
Blender freezes when exporting with shapekeys

### ISSUE THREAD

**Issue by songproducer** [godotengine/collada-exporter#41]
```
Traceback (most recent call last):
  File "/Applications/Blender2.78.app/Contents/Resources/2.78/scripts/addons/io_scene_dae/export_dae.py", line 1938, in save
    exp.export()
  File "/Applications/Blender2.78.app/Contents/Resources/2.78/scripts/addons/io_scene_dae/export_dae.py", line 1848, in export
    self.export_scene()
  File "/Applications/Blender2.78.app/Contents/Resources/2.78/scripts/addons/io_scene_dae/export_dae.py", line 1497, in export_scene
    self.export_node(obj, 2)
  File "/Applications/Blender2.78.app/Contents/Resources/2.78/scripts/addons/io_scene_dae/export_dae.py", line 1455, in export_node
    self.export_node(x, il)
  File "/Applications/Blender2.78.app/Contents/Resources/2.78/scripts/addons/io_scene_dae/export_dae.py", line 1442, in export_node
    self.export_mesh_node(node, il)
  File "/Applications/Blender2.78.app/Contents/Resources/2.78/scripts/addons/io_scene_dae/export_dae.py", line 1031, in export_mesh_node
    meshdata = self.export_mesh(node, armature)
  File "/Applications/Blender2.78.app/Contents/Resources/2.78/scripts/addons/io_scene_dae/export_dae.py", line 416, in export_mesh
    md = self.export_mesh(node, None, k, None, shape.name)
  File "/Applications/Blender2.78.app/Contents/Resources/2.78/scripts/addons/io_scene_dae/export_dae.py", line 686, in export_mesh
    v.normal.x, v.normal.y, v.normal.z)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Blender2.78.app/Contents/Resources/2.78/scripts/addons/io_scene_dae/__init__.py", line 159, in execute
    return export_dae.save(self, context, **keywords)
  File "/Applications/Blender2.78.app/Contents/Resources/2.78/scripts/addons/io_scene_dae/export_dae.py", line 1938, in save
    exp.export()
  File "/Applications/Blender2.78.app/Contents/Resources/2.78/scripts/addons/io_scene_dae/export_dae.py", line 1933, in __exit__
    bpy.data.meshes.remove(mesh)
RuntimeError: Error: Mesh 'Mesh.002' must have zero users to be removed, found 1 (try with do_unlink=True parameter)


```

**Comment by set-killer** [comment]
Nope. It's working. You have another problem in your blend file.
```
RuntimeError: Error: Mesh 'Mesh.002' must have zero users to be removed, found 1 (try with do_unlink=True parameter)
```

**Comment by paper-pauper** [comment]
Indeed, I tried it with [this sample model](https://wiki.blender.org/index.php/File:ManAnimationTechsShapeKeysExRSKFace.blend) and it worked. However, just to be safe, is there a more Shape Keys-heavy model around on OpenGameArt or somewhere? Just so that the issue can be closed safely..

**Comment by songproducer** [comment]
I was using a model created with [Manuel Bastioni's addon](http://www.manuelbastioni.com/download.php) v1.3 which has a lot of shape keys.

They've just released v1.4

**Comment by mutato** [comment]
That's true for all versions of Manuel Bastioni's addon. I encountered this error myslef and looked into it a bit. It seems something changed from Blender version 2.76 to 2.77. So I switched to Blender version 2.76 and it was working as expected. Since v2.76 is enough for me I didn't look into it, but it seemed there was a relative easy fix available but I don't know how compatible it is with older Blender versions.

**Comment by mysticfall** [comment]
I also experienced reproducible freezes trying to export a model created with Manuel Bastioni Lab. In my case, it's Blender 2.79b with MBLab 1.6 and the exporting process never finishes and makes the computer unusable eventually, possibly by exhausting memory.

**Comment by earlroxas13** [comment]
Hi guys,
I also experienced this, but not with Manuel Model but with MMD. I used [this blender addon](https://github.com/sugiany/blender_mmd_tools) to import MMD model (.pmx) to Blender. And [this model](http://imaginegirls.com/downloads_en/) to test (R1N4, the one in the bottom of the page).

The shape keys in the Model is for facial expression. And the mesh is full body, I tried to export the shape key and eventually i can't because of not enough memory problem. So i thought that if I separate the head with the rest of the mesh, because the shape keys is only facial expression, the export process will be much faster. And yes, it only several seconds to export, and the morph is working too in Blender. But when I import it to Godot the model is broken.

This is screenshot in blender, and [here is the model](http://kbagi.com/earlroxas/gd-651121/mmdr1n4reqskseparatedhead,5994233,gallery,1,1.blend) if you need it (you might need to enable sugiany mmd_tools add-on in Blender which I link on the top of my comment)
![meshblender](https://user-images.githubusercontent.com/8316851/39501367-ab09c442-4de4-11e8-81bf-6903ac4c8ff8.jpg)
And this is when imported to Godot.
![meshdaxport](https://user-images.githubusercontent.com/8316851/39501390-bdc27bb0-4de4-11e8-92d7-762486826104.jpg)


I dont really know of the shape keys workflow, so is it wrong to separate the head? or is it the exporter problem?

**Comment by mysticfall** [comment]
It seems that out of 83 shape keys that Manuel Bastioni Lab character has, the exporting process freezes around 32nd keys on my PC which has 16Gb of memory.

**Comment by mysticfall** [comment]
I tried to delete every shape keys other than a couple of them to see if it'd succeed. It did after a while, but it resulted in a `.dae` file which exceeds 1Gb in size.

On the other hand, if I export it using the default Collada exporter shipped with Blender, all 32 shape keys are exported to a file which is about 250mb in size.

Not sure if it'd help debugging the issue, but that's all I can find about the problem without going deeper into the code.
