### ISSUE TITLE
Export error: TypeError: endswith first arg must be str or a tuple of str, not frozenset

### ISSUE THREAD

**Issue by Snimchenko** [godotengine/collada-exporter#73]
When i export the model,i receive the following error:
`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_dae\__init__.py", line 172, in execute
    return export_dae.save(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_dae\export_dae.py", line 1966, in save
    exp.export()
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_dae\export_dae.py", line 1876, in export
    self.export_scene()
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_dae\export_dae.py", line 1522, in export_scene
    self.export_node(obj, 2)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_dae\export_dae.py", line 1467, in export_node
    self.export_mesh_node(node, il)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_dae\export_dae.py", line 1051, in export_mesh_node
    meshdata = self.export_mesh(node, armature)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_dae\export_dae.py", line 601, in export_mesh
    mat, mesh.show_double_sided)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_dae\export_dae.py", line 255, in export_material
    imgid = self.export_image(ts.texture.image)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_dae\export_dae.py", line 189, in export_image
    if img_tmp_path.lower().endswith(bpy.path.extensions_image):
TypeError: endswith first arg must be str or a tuple of str, not frozenset
 `

**Comment by dasreyh** [comment]
Having the same issue :(

**Comment by dasreyh** [comment]
tried getting help from a discord server for blender, someone said that:

"the author needs to change:

if img_tmp_path.lower().endswith(bpy.path.extensions_image):
to ->
if img_tmp_path.lower().endswith(tuple(bpy.path.extensions_image)):"

**Comment by Seabass247** [comment]
Its also a problem for me as well.  Needs a fix

**Comment by set-killer** [comment]
Created a pull request, but unfortunately I don't have suitable models to test if it works or not. Can you guys test it and confirm if it works or not before merging it?

**Comment by dasreyh** [comment]
Hey, mate. Seems to work for me! 

Before and afters.

Exporting before update:
![before](https://user-images.githubusercontent.com/6766693/42530408-140aae52-844f-11e8-80b2-582a428671aa.png)
Exporting after update:
![after](https://user-images.githubusercontent.com/6766693/42530422-1c87493c-844f-11e8-96f4-5dcca9648d0d.png)
No errors!

My model turns pink though now, not sure if that is due to the exporter though? Can be fixed by re applying the material.

**Comment by akien-mga** [comment]
Fixed by #78.
